config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :attachments
  resources :testimonials
  resources :services
  resources :blogs
  devise_for :users
  resources :portfolios

     root 'home#index'
     get '/dashboard' => 'dashboard#index'
     get '/dashboard/portfolio' => 'dashboard#portfolio'
     get '/dashboard/team' => 'dashboard#team'
     get '/dashboard/settings' => 'dashboard#settings'
     post '/dashboard/settings' => 'dashboard#save_settings'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	layout "adminlayout"
	before_action :authenticate_user!

	def index
		
	end

	def show
		# @ins =  Portfolio.new
		# @ins.show
		 # render 'portfolio'
	end

	def portfolio
		@portfolios = Portfolio.all
	end

	def blog
		@blogs = Blog.all
	end

	def service
		@services = Service.all
	end

	def testimonial
		@testimonials = Testimonial.all
	end

	def settings

		@fb_link = SiteConfig.fb_link
		@twitter_link = SiteConfig.twitter_link
		@gplus_link = SiteConfig.gplus_link
		@linked_link = SiteConfig.linked_link
		@flicker_link = SiteConfig.flicker_link
		@text_hex = SiteConfig.text_hex
		@number = SiteConfig.number
		@s1  = SiteConfig.s1
		@s2  = SiteConfig.s2
		@s3  = SiteConfig.s3
		@s4  = SiteConfig.s4
		@s5  = SiteConfig.s5
		@s6  = SiteConfig.s6

	end

	def save_settings
		
		SiteConfig.fb_link = params[:fb_link] 
		SiteConfig.twitter_link = params[:twitter_link] 
		SiteConfig.gplus_link = params[:gplus_link] 
		SiteConfig.linked_link = params[:linked_link] 
		SiteConfig.flicker_link = params[:flicker_link] 
		#SiteConfig.img = params[:img]
		SiteConfig.number  = params[:number]
		SiteConfig.s1 = params[:s1]
		SiteConfig.s2 = params[:s2]
		SiteConfig.s3 = params[:s3]
		SiteConfig.s4 = params[:s4]
		SiteConfig.s5 = params[:s5]
		SiteConfig.s6 = params[:s6]
		redirect_to :back, notice: "Data Save!"
	end

	def team
		@teams = Team.all
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/portfolio.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Portfolios</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Featured image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.title %></td>
        <td><%= image_tag portfolio.featured_image.thumb.url %></td>
        <td><%= portfolio.description %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
        <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/dashboard/settings.html.erb
<%= form_tag('/dashboard/settings',class: "form-group") do %>
  <div class="field"> 
    <%= label_tag :fb_link %><br>
    <%= text_field_tag :fb_link,@fb_link, class: "form-control" %>
  </div>
  <div class="field"> 
    <%= label_tag :twitter_link %><br>
    <%= text_field_tag :twitter_link,@twitter_link, class: "form-control" %>
  </div>
  <div class="field"> 
    <%= label_tag :gplus_link %><br>
    <%= text_field_tag :gplus_link,@gplus_link, class: "form-control" %>
  </div>
  <div class="field"> 
    <%= label_tag :linked_link %><br>
    <%= text_field_tag :linked_link,@linked_link, class: "form-control" %>
  </div>
  <div class="field"> 
    <%= label_tag :flicker_link %><br>
    <%= text_field_tag :flicker_link,@flicker_link, class: "form-control" %>
  </div>
  <!-- <div class="field">
    <%= label_tag :img %><br>
    <%= file_field_tag :img, class: "form-control" %>
  </div> -->
  <div class="field">
    <%= label_tag :number %><br>
    <%= text_field_tag :number,@number, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s1 %><br>
    <%= text_field_tag :s1,@s1, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s2 %><br>
    <%= text_field_tag :s2,@s2, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s3 %><br>
    <%= text_field_tag :s3,@s3, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s4 %><br>
    <%= text_field_tag :s4,@s4, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s5 %><br>
    <%= text_field_tag :s5,@s5, class: "form-control",required: "" %>
  </div>
  <div class="field">
    <%= label_tag :s6 %><br>
    <%= text_field_tag :s6,@s6, class: "form-control",required: "" %>
  </div>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/dashboard/team.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Teams</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Profile</th>
      <th>Post</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.name %></td>
        <td><%= image_tag team.profile.thumb.url %></td>
        <td><%= team.post %></td>
        <td><%= team.detail %></td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_team_path %>