config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :attachments
  resources :testimonials
  resources :services
  resources :blogs
  devise_for :users
  resources :portfolios

     root 'home#index'
     get '/dashboard' => 'dashboard#index'
     get '/dashboard/portfolio' => 'dashboard#portfolio'
     get '/dashboard/team' => 'dashboard#team'
     get '/dashboard/settings' => 'dashboard#settings'
     post '/dashboard/settings' => 'dashboard#save_settings'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :attachments
	accepts_nested_attributes_for :attachments
	#mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  	@post_attachments = @blog.attachments.all
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @post_attachments = @blog.attachments.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
      	params[:post_attachments]['image'].each do |a|
          @post_attachment = @blog.attachments.create!(:image => a)
       	end
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :image, :desc, post_attachments_attributes: [:id, :blog_id, :image])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, :html => { :multipart => true }, class: "form") do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"  %>
  </div>

    
  <%= f.fields_for :post_attachments do |p| %>
   <div class="field">
     <%= p.label :image %><br>
     <%= p.file_field :image, :multiple => true, name: "post_attachments[image][]" %>
   </div>
  <% end %>


  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc,  class: "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= image_tag blog.attachments.first.image.thumb.url %></td>
        <td><%= blog.desc %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="post">
	<div class="post-title-enclose">
		<h2><%= @blog.title %></h2>
		<div class="post-info">
			<ul class="blog-tile-post-info">
			<li>Post by <a href="">Admin</a></li>
			<li><i class="fa fa-select"></i><a href="#"><%= @blog.created_at.strftime("%m-%d-%Y") %></a></li>
		</ul>
		</div>
	</div>
	<div class="post-content-wrap">
		<div class="featured-image">
		<img class="img-responsive" src="<%= @post_attachments.first.image.url %>" alt="">
		</div>
		<div class="post-content"><%= @blog.desc %>
		<!-- <a href="" class="rmore clearfix btn pull-right">Read More!</a> -->
		</div>
	</div>
</div>
<!-- <p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Image:</strong>
  <% @post_attachments.each do |p| %>
  <%= image_tag p.image %>
	  <%= link_to "Edit Attachment", edit_attachment_path(p) %>
	<% end %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @blog.desc %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
 -->