config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :attachments
  resources :testimonials
  resources :services
  resources :blogs
  devise_for :users
  resources :portfolios

     root 'home#index'
     get '/dashboard' => 'dashboard#index'
     get '/dashboard/portfolio' => 'dashboard#portfolio'
     get '/dashboard/team' => 'dashboard#team'
     get '/dashboard/settings' => 'dashboard#settings'
     post '/dashboard/settings' => 'dashboard#save_settings'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
		mount_uploader :image, ImageUploader
		belongs_to :blog
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment.blog, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:image)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= image_tag @attachment.image, class: "img-responsive" %>
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= image_tag attachment.image %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @attachment.image %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>