config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :attachments
  resources :testimonials
  resources :services
  resources :blogs
  devise_for :users
  resources :portfolios

     root 'home#index'
     get '/dashboard' => 'dashboard#index'
     get '/dashboard/portfolio' => 'dashboard#portfolio'
     get '/dashboard/team' => 'dashboard#team'
     get '/dashboard/settings' => 'dashboard#settings'
     post '/dashboard/settings' => 'dashboard#save_settings'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	mount_uploader :profile_pic, ImageUploader
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:profile_pic, :client_name, :company_name, :comment, :star)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial, class:'form') do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.file_field :profile_pic, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.number_field :star, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Testimonials</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Profile pic</th>
      <th>Client name</th>
      <th>Company name</th>
      <th>Comment</th>
      <th>Star</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= image_tag testimonial.profile_pic.thumb.url %></td>
        <td><%= testimonial.client_name %></td>
        <td><%= testimonial.company_name %></td>
        <td><%= testimonial.comment %></td>
        <td><%= testimonial.star %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile pic:</strong>
  <%= image_tag @testimonial.profile_pic, class:"showImage" %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @testimonial.client_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @testimonial.company_name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @testimonial.comment %>
</p>

<p>
  <strong>Star:</strong>
  <%= @testimonial.star %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>